# Generated by Django 5.1.5 on 2025-02-16 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepFake', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Media File', 'verbose_name_plural': 'Media Files'},
        ),
        migrations.AddField(
            model_name='mediafile',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='ela_image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='frame_analysis_image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='jpeg_image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='noise_image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='prediction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='spectrogram_image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediafile',
            name='waveform_image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
