"""
Django settings for deepFakeDetection project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import importlib.util
import os
import sys

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# PyMySQL: no system mariadb-devel required (set DB_USE_MYSQLCLIENT=1 to use mysqlclient instead)
if os.environ.get('DB_USE_MYSQLCLIENT', '').lower() not in ('1', 'true', 'yes'):
    try:
        import pymysql
        pymysql.version_info = (2, 2, 7, 'final', 0)
        pymysql.install_as_MySQLdb()
    except ImportError:
        pass


def _env_bool(name: str, default: bool = False) -> bool:
    return os.environ.get(name, str(default)).lower() in ('true', '1', 'yes')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-ftsm$17tc@ydhkn(^s&+#p5ld5jlk!(1jun&k6%ld^auyguk_t',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', default=False)

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]

# Trust X-Forwarded-Proto when behind Nginx (HTTPS termination)
if os.environ.get('USE_X_FORWARDED_HOST', '1').lower() in ('1', 'true', 'yes'):
    USE_X_FORWARDED_HOST = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'deepFake',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

def _module_installed(name: str) -> bool:
    return importlib.util.find_spec(name) is not None


if DEBUG:
    for _dev_app in ('livereload', 'tailwind', 'django_browser_reload'):
        if _module_installed(_dev_app):
            INSTALLED_APPS.append(_dev_app)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG and _module_installed('livereload'):
    MIDDLEWARE.insert(2, 'livereload.middleware.LiveReloadScript')
if DEBUG and _module_installed('django_browser_reload'):
    MIDDLEWARE.append('django_browser_reload.middleware.BrowserReloadMiddleware')

ROOT_URLCONF = 'deepFakeDetection.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'deepFakeDetection.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'ml_db'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'admin'),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS = [
    "127.0.0.1",
]
# STATICFILES_DIRS = [
#     BASE_DIR / 'deepFake' / 'static',
# ]
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'deepFake' / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Base directory containing your models
MODELS_DIR = os.path.join(BASE_DIR, 'deepFake', 'mlModel')

# Model paths
MODEL_PATHS = {
    'image_model': os.path.join(MODELS_DIR, 'custom_augmented_model.h5'),
    'video_model': os.path.join(MODELS_DIR, 'deepfake_detection_model.h5'),
    'audio_model': os.path.join(MODELS_DIR, 'deep_fake_audio_detector.h5'),
}

# Exiftool: bundled .exe on Windows, system binary on Linux (apt: libimage-exiftool-perl)
if os.environ.get('EXIFTOOL_PATH'):
    EXIFTOOL_PATH = os.environ['EXIFTOOL_PATH']
elif sys.platform == 'win32':
    EXIFTOOL_PATH = os.path.join(MODELS_DIR, 'exiftool.exe')
else:
    EXIFTOOL_PATH = 'exiftool'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}
